all:Puntoc/Punto3Main.class

Puntoc/Punto3Main.class: Puntoc/Punto3Main.java
	javac Puntoc/*.java
	
clean:
	$(RM) Puntoc/*.class Punto3Main.jar
run:
	java Puntoc/Punto3Main D:\organizacion\Proyecto_Organizacion_Final\Paralelismo\Puntoa\DB.csv