all:src/Punto3Main.class src/Punto3.class src/Master.class src/Consumer.class

src/Punto3Main.class: src/Punto3Main.java
	javac src/*.java
	
clean:
	$(RM) src/*.class Punto3Main.jar
run:
	java src/Punto3Main DB.csv